[profile]
debug = true


[toolchain]
channel = "nightly"

# Configure builds for our target, the micro:bit's architecture
[target.thumbv6m-none-eabi]
# Execute binary using gdb when calling cargo run
runner = "gdb-multiarch"
# Tweak to the linking process required by the cortex-m-rt crate
rustflags = [
    #"-C", "linker=arm-none-eabi-gcc",
    "-C", "link-arg=-Tlink.x",
    # The LLD linker is selected by default
    #"-C", "linker=arm-none-eabi-ld",
    #"-C", "linker=arm-none-eabi-gcc",
    #"-C", "linker=arm-none-eabi-gcc",
]

# Automatically select this target when cargo building this project
[build]
target = "thumbv6m-none-eabi"

